seed_everything: 42

model:
  class_path: models.RotationalVariationalAutoencoderPower
  init_args:
    encoder:
      class_path: models.ConvolutionalEncoder
    decoder:
      class_path: models.ConvolutionalDecoder
    h_dim: 256
    z_dim: 3
    image_size: 363
    rotations: 36
    beta: 1.0e-3

data:
  class_path: data.IllustrisSdssDataModule
  init_args:
    data_directories: ["TNG100", "TNG50", "Illustris"]
    extension: fits
    minsize: 100
    batch_size: 512
    shuffle: True
    num_workers: 16

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001

lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    mode: min
    factor: 0.1
    patience: 5
    cooldown: 5
    min_lr: 1.e-5
    monitor: train_loss
    verbose: True

trainer:
  max_epochs: 200
  accelerator: gpu
  devices: 4
  precision: 32

  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: spherinator
      log_model: True
      entity: ain-space
      tags:
        - illustris

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: train_loss
        filename: "{epoch}-{train_loss:.2f}"
        save_top_k: 3
        mode: min
        every_n_epochs: 1
    - class_path: callbacks.LogReconstructionCallback
      init_args:
        num_samples: 6
